# Generated by Django 3.2 on 2022-02-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactEmail',
        ),
    ]
